### ISSUE TITLE
这个Profile是用啥生成的？

### ISSUE THREAD

**Issue by trim21** [llxlr/llxlr#3]

**Comment by trim21** [comment]
好象不是现在这个github actions？

**Comment by llxlr** [comment]
> 好象不是现在这个github actions？

你指的什么？之前那个wakatime吗？看到你用上了

**Comment by trim21** [comment]
Platforms & tools 这些

**Comment by llxlr** [comment]
> Platforms & tools 这些

这些是一个个手动加上的，看我的[README.md](https://raw.githubusercontent.com/llxlr/llxlr/master/README.md)里面，那些badge图标用的[Shields.io](https://shields.io/)生成的，然后用链接嵌着badge图标。Shield用的是[Simple Icons](https://simpleicons.org/)里的图标，你可以在里面搜到你想要的，当然不一定有，matlab就没有

**Comment by llxlr** [comment]
> Platforms & tools 这些



> > Platforms & tools 这些
> 
> 这些是一个个手动加上的，看我的[README.md](https://raw.githubusercontent.com/llxlr/llxlr/master/README.md)里面，那些badge图标用的[Shields.io](https://shields.io/)生成的，然后用链接嵌着badge图标。Shield用的是[Simple Icons](https://simpleicons.org/)里的图标，你可以在里面搜到你想要的，当然不一定有，matlab就没有

B站和推特的关注接口用的[Substats](https://substats.spencerwoo.com/)

**Comment by trim21** [comment]
感谢
